### ISSUE TITLE
sample_encode doesn`t work in case of enabled VPP and internal memory allocator

### ISSUE THREAD

**Issue by Fantast34** [oneapi-src/oneVPL#10]
sample_encode h265 -i input_1920x1080.nv12 -o output.hevc -w 1920 -h 1080 -nv12 -dstw 1280 -dsth 720 -api2x_dispatcher -api2x_internalmem
doesn`t work because output surface for VPP instance = NULL

**Comment by mav-intel** [comment]
api2x_internalmem is no longer supported by sample_encode

**Comment by Fantast34** [comment]
Hi @mav-intel ,
Could you please clarify plans for legacy tools (sample_encode and sample_decode)? Will you support them in context of oneVPL? 
Will you support internal memory allocators at all?
