### ISSUE TITLE
MFXCreateSession failing with older Intel drivers

### ISSUE THREAD

**Issue by jbrownsw** [oneapi-src/oneVPL#105]
I ran into this issue when I upgraded to ffmpeg 6 and enabled onevpl on it. Compiling without onevpl worked for the older drivers where it uses MFXInit, but not with onevpl and MFXCreateSession. I created a ticket for ffmpeg to workaround the issue, but I think the real solution should be in onevpl. I don't have too many details at the onevpl level because I was going through ffmpeg, but I believe it was returning `MFX_ERR_NOT_FOUND`. That's probably not too much help since most errors in MFXCreateSession will return that. One of the systems was an Intel HD Graphics 4400 driver 20.19.15.4531 from 9/29/2016. The other system I'm mostly going on memory from was an Intel UHD 500 with a driver from 2018.

The ffmpeg ticket I created with my workaround is:
https://trac.ffmpeg.org/ticket/10537

**Comment by akwrobel** [comment]
Hi @jbrownsw we will monitor this issue and the one you filed with the QSV team to see what impact this may have on oneVPL.

**Comment by akwrobel** [comment]
The platforms mentioned are not currently in our support matrix, and there are no current plans to add this support.
