### ISSUE TITLE
HEVC hardware plugin support for old intel drivers on Windows?

### ISSUE THREAD

**Issue by paniksystem** [oneapi-src/oneVPL#106]
oneVPL dispatcher fails to encode HEVC on old intel drivers (most recent from Windows Update on Windows 10, drivers version 22.20.16.4815), i have a i5-7200U which works with ffmpeg 5.1 using the old mfx dispatcher, but the new oneVPL dispatcher has no support for loading the HW HEVC plugin using MFXVideoUSER_Load which is needed for this MSDK runtime version (1.25). Is this by design or is it planned to be supported in the future?

**Comment by tletnes** [comment]
MSDK Plugins were removed in [API v2.0](https://spec.oneapi.io/versions/latest/elements/oneVPL/source/VPL_intel_media_sdk.html#msdk-full-name-feature-removals). HEVC support has been moved to the runtime with [newer driver releases](https://www.intel.com/content/www/us/en/download-center/home.html) and does not require plugins. There is no plan to reintroduce the plugin subsystem.

**Comment by paniksystem** [comment]
Thank you
