### ISSUE TITLE
sample_encode causes Segmentation fault in case of video memory + internal allocator

### ISSUE THREAD

**Issue by Fantast34** [oneapi-src/oneVPL#11]
sample_encode h265 -i input_1920x1080.nv12 -o output.hevc -w 1920 -h 1080 -nv12 -api2x_dispatcher -api2x_internalmem -vaapi
produces Segmentation fault

**Comment by mgonchar** [comment]
It might be related to https://github.com/oneapi-src/oneVPL/issues/18

**Comment by mav-intel** [comment]
Fixed in v2021.4.0 (d5c0725)
