### ISSUE TITLE
Compile 32-bit libraries

### ISSUE THREAD

**Issue by xidiancpy** [oneapi-src/oneVPL#113]
My application requires a 32-bit library, but I don't know how to compile it?

**Comment by mav-intel** [comment]
@xidiancpy You will need to build directly with CMake.  If your generator supports multiple architectures you can use :

> -A <platform-name>[¶](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-A)
> Specify platform name if supported by generator.
> 
> Some CMake generators support a platform name to be given to the native build system to choose a compiler or SDK. See the [CMAKE_GENERATOR_PLATFORM](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_PLATFORM.html#variable:CMAKE_GENERATOR_PLATFORM) variable for details.

**Comment by xidiancpy** [comment]
got it
