### ISSUE TITLE
sample_encode incorrect workflow with VPL memory

### ISSUE THREAD

**Issue by mgonchar** [oneapi-src/oneVPL#18]
sample_encode releases surface before usage. Correct workflow is to call Release after surface is no longer needed, i.e. submitted to encoder. See preliminary fix https://github.com/oneapi-src/oneVPL/pull/17

**Comment by mav-intel** [comment]
Fixed in [v2021.5.0](https://github.com/oneapi-src/oneVPL/releases/tag/v2021.5.0)
