### ISSUE TITLE
GPL-3.0 incompatible licenses: MS Visual Studio

### ISSUE THREAD

**Issue by sndirsch** [oneapi-src/oneVPL#27]
In third-party-programs.txt "MS Visual Studio" licenses are mentioned. These are not GPL 3.0 compatible, i.e. you can't link GPL 3.0 sources against libvpl. This makes it difficult for a Linux distributor to ship this library. :-(

Is this an oversight, intentional or just can't be changed?

**Comment by dvrogozh** [comment]
@sndirsch : can you, please, point to specific code which is of concern? I afraid I don't quite understand which piece of code you are talking about.

**Comment by sndirsch** [comment]
I can't. I only see it mentioned in https://github.com/oneapi-src/oneVPL/blob/master/third-party-programs.txt. If there isn't such code in there, fine. But then You could remove it from this file, right?

**Comment by mav-intel** [comment]
If you build on Windows,  CMake's InstallRequiredSystemLibraries is used to allow the resulting installation to be deployed on a system without Visual Studio. This particular distribution would not be GPL 3.0 compatible.  We use this when distributing our Windows binary release as part of the oneAPI Basekit, which is not distributed under a GPL license.

Is there a better way to make this clear to readers? We have a related issue in oneVPL-cpu where you can build for gpl or mit licenses

**Comment by sndirsch** [comment]
Thanks! On Linux we're using cmake/make/gcc for building and installation (me talking about (open)SUSE here), so my understanding would be, that this a non-issue for us. Is this correct?

In order to make this more clear you could mention, that these "MS Visual Studio" licenses only apply when installing this software on Windows as part of the oneAPI BaseKit.

**Comment by mav-intel** [comment]
Yes that is correct, if you are building using GCC targeting a Linux environment it is a non-issue for you. The visual studio runtimes are only installed if you build on Windows using visual studio.

**Comment by sndirsch** [comment]
Thanks a lot! That's great news!

**Comment by sndirsch** [comment]
Maybe you can add to the" MS Visual Studio" licenses:

"Only relevant when building on Windows using Visual Studio. In this case the Visual Studio runtimes are installed to the system under these licenses."

Or something like this ...

**Comment by sndirsch** [comment]
Feel free to close the ticket. Thanks a lot for your comments!

**Comment by mav-intel** [comment]
Next update will include updates to the test in the third party file to make clear when Microsoft license is relevant

**Comment by sndirsch** [comment]
> Next update will include updates to the test in the third party file to make clear when Microsoft license is relevant

Thanks. Sounds great! :-)
