### ISSUE TITLE
how to use tracer.exe to dump msdk log messages on Windows

### ISSUE THREAD

**Issue by tong1wu** [oneapi-src/oneVPL#28]
I am using the open source oneVPL dispatcher and the inner-source mdp-msdk-lib to build the runtime. After I downloaded the tracer.exe from msdk official website and pressed the start button, no bytes are written into the log file. Does the runtime that I'm using have to be the msdk runtime in the dev package? I put the libmfx64-gen.dll which I built myself under C:\Windows\System32 and seems that tracer.log doesn't react to it when I run the application to call the runtime.

**Comment by dmitryermilov** [comment]
@IgorBelyakovIntel , @jonrecker , can you please help?

**Comment by jonrecker** [comment]
The MediaSDK tracer tool only supports MSDK dispatcher and runtimes. Basic logging in the oneVPL dispatcher can be enabled by setting the environment variable ONEVPL_DISPATCHER_LOG=ON (more info [here](https://spec.oneapi.io/onevpl/latest/programming_guide/VPL_prg_session.html#onevpl-dispatcher-debug-log)). Future versions of oneVPL dispatcher are expected to provide more detailed logging, similar to what is available with MSDK tracer.

**Comment by tong1wu** [comment]
Thanks, going to close this issue.
