### ISSUE TITLE
Fix hardening flags

### ISSUE THREAD

**Issue by onabiull** [oneapi-src/oneVPL#3]
RELRO options should appear in linker flags.
Preferably in form:
```
target_link_options(VPL PRIVATE
  LINKER:--version-script=${CMAKE_CURRENT_SOURCE_DIR}/libVPL.map
  LINKER:--no-undefined,-z,relro,-z,now,-z,noexecstack
  -fstack-protector
  )
```

**Comment by mav-intel** [comment]
Hi.  
These flags are being applied via cmake/CompileOptions.cmake
You can verify that they are applied to the binaries by running [hardening-check](http://manpages.ubuntu.com/manpages/trusty/man1/hardening-check.1.html) against the so
