### ISSUE TITLE
version.txt mismatches v2022.0.1 tag name

### ISSUE THREAD

**Issue by dvrogozh** [oneapi-src/oneVPL#30]
https://github.com/oneapi-src/oneVPL/blob/301d5736f86c433e68dbe24b649e2798ecd13a0c/version.txt#L1

Tag v2022.0.1 and version.txt mismatch.

**Comment by mav-intel** [comment]
Will be fixed in next release by removing version.txt at root of repository. This is used for internal packaging only

**Comment by mav-intel** [comment]
Fixed in v2022.0.2
