### ISSUE TITLE
Weird platform check for MediaSDK vs VPL loading

### ISSUE THREAD

**Issue by dmitryermilov** [oneapi-src/oneVPL#5]
Please see https://github.com/oneapi-src/oneVPL/blob/17968d8d2299352f5a9e09388d24e81064c81c87/dispatcher/linux/mfxloader.cpp#L202-L211.

Platforms are defined here: https://github.com/oneapi-src/oneVPL/blob/17968d8d2299352f5a9e09388d24e81064c81c87/dispatcher/linux/device_ids.h#L382-L406

Please confirm (or not) that this is the expected and correct behavior that VPL is used only after ADL.

**Comment by jonrecker** [comment]
This logic is only used when initializing via MFXInit() / MFXInitEx() and is intended to align with behavior of the MediaSDK dispatcher. (see PR [here](https://github.com/Intel-Media-SDK/MediaSDK/pull/2692)) For platforms in the device_ids list, load libmfx. For all others, load oneVPL. device_ids.h should be updated when VPL support is enabled for a platform in this list.

When using MFXLoad() / MFXCreateSession() the logic for using VPL or MediaSDK is handled by the VPL loader, and the [full path](https://github.com/oneapi-src/oneVPL/blob/17968d8d2299352f5a9e09388d24e81064c81c87/dispatcher/linux/mfxloader.cpp#L192) of the library to load is passed in to this function.
