### ISSUE TITLE
[ATS-M3]Sample decode should not use vebox

### ISSUE THREAD

**Issue by xinyudox** [oneapi-src/oneVPL#54]
os: ubuntu 20.04
kernel: 5.10.54+prerelease2400
oneVPL: 3470ecd8ee4b69d15c6ab06c369d52ce8d23746f
libva: dad7abcb958b97b50c318dd42a477e035a42e358
ffmpeg: 534c4db1800ebdb1e7dab031a63413d74bab4bf8
gmmlib: 29152fc6d39f87983b176664f225d42af039f716
media-driver: c8decb7f6e8bc1c77f6becdbe7bbe0e1697d62e8

cmd:
./sample_decode h264 -i 1080p60fps.264 -o /dev/null -hw -vaapi
test result:
fps  channels  vdbox1  vdbox2  vebox  
30     60          52.82%   52.23%  100%

The usage rate of vebox should be 0%.

**Comment by dmitryermilov** [comment]
Hi @xinyudox ,

What is the result of running without -o option?

**Comment by xinyudox** [comment]
sorry, unpublished platforms, close it.
