### ISSUE TITLE
The latest version is not uploaded on NuGet 

### ISSUE THREAD

**Issue by karasusan** [oneapi-src/oneVPL#60]
Hi, I checked the manual to install oneVPL, and I am trying it according this doc below.
https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-windows/top/installation/install-using-package-managers/nuget.html

But I noticed the latest version of the package have not been uploaded yet. 
https://www.nuget.org/packages/onevpl.devel.win-x64
https://www.nuget.org/packages/onevpl.devel.linux-x64

I assume that NuGet hosting is not maintained frequently.
I would like to know the best way to install the oneVPL package. Should we check out from this repository?

**Comment by tletnes** [comment]
Hi

Is where there is confusion. The packages on Nuget are published as part of Intel's OneAPI project which releases quarterly. The long release cycle allows many components to be tested together and published to a variety of locations.

This repo is directly managed by the OneVPL team and it is where we publish all of our regular releases. This includes the code that will be in OneAPI releases, as well as releases that will be packaged with graphics drivers, and any other public release.

If you want the latest OneVPL release please take the most recent release version tagged in this repository. The INSTALL.md file should provide instructions on building and installing OneVPL. If you have questions or problems following them please reach out here so we can help you, and improve our documentation.

I hope this helps.

**Comment by karasusan** [comment]
All right. Thank you for explaing the detail.
I closed this issue.
