### ISSUE TITLE
Passing a user data pointer along with a frame when encoding video

### ISSUE THREAD

**Issue by gizahNL** [oneapi-src/oneVPL#64]
I want to pass a pointer to metadata belonging to my application along with a frame and retrieve the associated pointer. Unfortunately I haven't seen any straightforward way to do that. Is passing a user pointer along with a frame when queuing for encoding and retrieving along with bitstream supported?

**Comment by jeffreymcallister** [comment]
Timestamps may provide what you are looking for.  You can see examples of using timestamps to hold application metadata here:

- [Media SDK low latency transcode tutorial](https://github.com/Intel-Media-SDK/MediaSDK/tree/master/tutorials/simple_6_transcode_opaque_lowlatency)
- [Media SDK low latency encode tutorial](https://github.com/Intel-Media-SDK/MediaSDK/tree/master/tutorials/simple_6_encode_vmem_lowlatency)

Timestamps are designed to carry container data through the pipeline

- decode: bitstream in->frame out
- vpp:frame in->frame out
- encode: frame in->bitstream out

This timestamp data doesn't affect decode, vpp, or frame operations.  If the data attached to each frame is reinterpreted as a pointer, array index, hash, etc. you can work around the size limitation of the timestamp.

**Comment by gizahNL** [comment]
I'm not sure that would work with encode operations, as that could leak into HRD VPB calculations and other places and would lead to incorrect values in the encoded bitstream when it comes to timing.
