### ISSUE TITLE
Legacy tools use x86/x86_64 specific assembler code

### ISSUE THREAD

**Issue by StefanBruens** [oneapi-src/oneVPL#69]
https://github.com/oneapi-src/oneVPL/blob/15b79165c30fc4a7bf6efdf261a39b128b63b896/tools/legacy/sample_common/src/vm/atomic_linux.cpp#L11-L17

This breaks build on ARM, PPC, RISC-V, ... 
oneVPL should be buildable on all platforms, as SW implementations and dGPU (Arc) is available there too.

Possible solutions
1. Make it a wrapper around C11 atomic_fetch_add
2. Disable legacy tools on anything but x86(_64)

**Comment by jeffreymcallister** [comment]
Thank you for reporting this issue. We are looking into options to resolve and will let you know as we make progress.

**Comment by mav-intel** [comment]
fixed In d69f50f5fd4113fd8bc861db65e838195316dafc
