### ISSUE TITLE
Typos in output: preffer -> prefer, preffered -> preferred

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/oneVPL#75]
Code has following typos in its output:
* preffer -> prefer
* preffered -> preferred (note 'rr')

See `git grep preffer` (and e.g. Oxford language dictionary).

PS. while this bug is about user visible output, `git grep Preffer` shows also typoed variable name.

**Comment by mav-intel** [comment]
Fixed in db5fca7c07bf09dc0b7df51456b3403ebfacb2ba

**Comment by eero-t** [comment]
Looks good, thanks!
