### ISSUE TITLE
"-svtav1-params" equivalent for av1_qsv encoder (to pass HDR10 mastering metadata)?

### ISSUE THREAD

**Issue by millercentral** [oneapi-src/oneVPL#87]
Hello, I am working to understand how to take advantage of the av1_qsv encoder with my A770 DG2 dGPU. I am trying to encode 10-bit AV1 files with HDR10, but I am struggling to understand how to encode the HDR10 metadata.

With svt-av1, you can pass in the parameters in ffmpeg using the "-svtav1-params" command-line option, for example:
`-c:v libsvtav1 -svtav1-params "preset=6:crf=13:tune=0:enable-hdr=1:color-primaries=9:transfer-characteristics=16:matrix-coefficients=9:mastering-display=G(0.265,0.69)B(0.15,0.06)R(0.68,0.32)WP(0.3127,0.329)L(4000.0,0.005):content-light=1000,755"`
(svtav1 parameters are all documented here: https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md ). The x265 encoder has an equivalent option (`x265-params`) as well. 

Is there a way to do the equivalent with the OneVPL / av1_qsv encoder in ffmpeg?

Thanks!

**Comment by mav-intel** [comment]
Transferred to https://github.com/intel/cartwheel-ffmpeg/issues/221

**Comment by xhaihao** [comment]
@mav-intel  FFmpeg QSV may accept HDR parameters from the input frame, however currently av1 encoder in oneVPL RT is not able to accept HDR parameters.  (hevc encoder has this feature).
