### ISSUE TITLE
dpcpp blur udf failing with error CL_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by pooja-intel** [oneapi-src/oneVPL#95]
The dpdpp blur udf is failing with the below mentioned error:
```
[Wed Apr 12 10:09:33 2023] ERROR:initialize:116: Failed to initialize UDF: No device of requested type available. Please check https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-system-requirements.html -1 (CL_DEVICE_NOT_FOUND)
```

Using the `intel-basekit 2023.1.0` version for linux downloaded using the apt package manager method.
Is there any workaround to resolve the above issue ?

**Comment by mav-intel** [comment]
Hi @pooja-intel , the dpcpp blur sample was removed a couple of releases ago, partly because it was not aligned with the latest dpcpp compiler advances.
