### ISSUE TITLE
ERROR: cannot create session -- no implementations meet selection criteria ERROR: not able to create VPL session

### ISSUE THREAD

**Issue by kmanisai** [oneapi-src/oneVPL#98]
Facing issue with the demo:

oneapi toolkit version : 2023.1 (https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=offline&version=2023.1)

System info:
Linux Ubuntu 22 Generic 5.19.0-42 

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Issue:

intel@ubuntu:~/oneapi/oneVPL/examples/interop/vpl-infer/build$ ./vpl-infer -i cars_320x240.h265 -m mobilenet-ssd.xml
OpenVINO Runtime
    Version : 2022.3.0
    Build   : 2022.3.0-9052-9752fafe8eb-releases/2022/3

Loading network model files: mobilenet-ssd.xml
    Model name: MobileNet-SSD
    Inputs
        Input name: data
        Input type: f32
        Input shape: [1,3,300,300]
    Outputs
        Output name: detection_out
        Output type: f32
        Output shape: [1,1,100,7]

**ERROR: cannot create session -- no implementations meet selection criteria
ERROR: not able to create VPL session**

**Comment by KomShin-TCE** [comment]
Hello Mav,

Please ensure you have set up your Graphics Driver with all the necessary dependencies:

**For general info**: https://dgpu-docs.intel.com/driver/installation.html >> Installation >> Installation Procedure
**For Ubuntu 22.04**: https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-legacy.html

If you have followed the installation procedures, so that you have all the dependencies in place, and are still experiencing difficulties, let us know.

Pamela

**Comment by kmanisai** [comment]
Hi Pamela,
Even with installing all the dependencies, I am still seeing the same error.

**Comment by KomShin-TCE** [comment]
Seems like you have the VPL dispatcher but there's no GPU runtime.

Please provide all the output from these command line executions:

lspci | grep VGA
ls /usr/lib/x86_64-linux-gnu/libmfx*
ls /dev/dri
vainfo

**Comment by kmanisai** [comment]
Hi Pamela, As you said after installing VPL dispatcher and onevpl-intel-gpu runtime i am able to avoid session error but i am seeing some cldnn error.

**intel@ubuntu:~/oneVPL/examples/interop/vpl-infer/build$ ./vpl-infer -i cars_320x240.h265 -m mobilenet-ssd.xml -zerocopy
OpenVINO Runtime
    Version : 2022.3.0
    Build   : 2022.3.0-9052-9752fafe8eb-releases/2022/3

Loading network model files: mobilenet-ssd.xml
    Model name: MobileNet-SSD
    Inputs
        Input name: data
        Input type: f32
        Input shape: [1,3,300,300]
    Outputs
        Output name: detection_out
        Output type: f32
        Output shape: [1,1,100,7]

libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0

oneVPL Implementation details:
    ApiVersion:           2.8
    AccelerationMode via: VAAPI
  DeviceID:             7d55/0
    Path: /usr/lib/x86_64-linux-gnu/libmfx-gen.so.1.2.8

libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
cldnn program build failed! Program build failed(0_part_3): You may enable OCL source dump to see the error log.**

Not getting what step i am missing.

**Comment by kmanisai** [comment]
As you asked i am providing command line outputs:

intel@ubuntu:~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Device 7d55
00:0b.0 Non-VGA unclassified device: Intel Corporation Device 7d1d (rev 01)
intel@ubuntu:~$ ls /usr/lib/x86_64-linux-gnu/libmfx*
/usr/lib/x86_64-linux-gnu/libmfx-gen.so        /usr/lib/x86_64-linux-gnu/libmfxhw64.so.1     /usr/lib/x86_64-linux-gnu/libmfx.so.1.35
/usr/lib/x86_64-linux-gnu/libmfx-gen.so.1.2    /usr/lib/x86_64-linux-gnu/libmfxhw64.so.1.35
/usr/lib/x86_64-linux-gnu/libmfx-gen.so.1.2.8  /usr/lib/x86_64-linux-gnu/libmfx.so.1

/usr/lib/x86_64-linux-gnu/libmfx-gen:
enctools.so
intel@ubuntu:~$ ls /dev/dri
by-path  card0  renderD128
intel@ubuntu:~$ vainfo
Trying display: wayland
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.19 (libva 2.18.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 (d3d2013e1)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
